### ISSUE TITLE
draft documentation promotion

### ISSUE THREAD

**Issue by thescientist13** [nodejs/package-maintenance#373]
We have a number of docs in [draft](https://github.com/nodejs/package-maintenance/tree/master/docs/drafts) status, but not sure what is left or needed.  They should probably all be reviewed and if complete "enough" should probably be at least moved into the top level docs folder.

This is a top level tracking item to promote them all
- [ ] Continuous Integration / Delivery (**assigned**) - #340
- [x] [Security (**assigned**)](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/security-guidelines.md) - #343
- [x] [Testing](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/testing-guidelines.md) - #344
- [x] [Publishing Guidelines (**assigned**)](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/publish-guidelines.md) - #345
- [x] [Package Support](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/package-support.md) - #346
- [x] ~~[Tools](https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/tools-guidelines.md)~~ - #347 (marked as **invalid**)
- [x] Dependency Management (**assigned**) - #280
- [x] [Deprecate Guidelines](https://github.com/nodejs/package-maintenance/blob/main/docs/drafts/DEPRECATE-GUIDELINES.md) - #431 (draft) - https://github.com/nodejs/package-maintenance/pull/487

Note: they should also have the "draft" status removed from their listing in the [Table of Contents](https://github.com/nodejs/package-maintenance/tree/master/docs).

**Comment by ghinks** [comment]
@thescientist13 thank you Owen, this does seem like something that I have time for. I'll look at the testing draft by @Eomm over the next week, make comments and get back.

**Comment by ghinks** [comment]
@thescientist13 I think the testing document is going well and we are only waiting on a few more reviews. It is a basic document but there are quite distinct schools of thought about testing.  
I would like to move onto the CI/CD document. @dominykas mentioned in the testing document review that we need real world methodologies of how and where we can do CI/CD for open source. I agree and I'll link the testing document to the CI/CD document once we get it written.

For myself I do not know quite enough to start this yet and want to talk in the next package maintenance meeting. What we need are a bunch of projects in opensource that do this so we have concrete examples.

**Comment by thescientist13** [comment]
Hey @ghinks , and sounds good to me.  Maybe we should add the agenda label to #340 and then we can discuss it on the call this week?  Happy to help contribute ideas and topics for the document as well.  👎

**Comment by ghinks** [comment]
@thescientist13 the testing doc is looking good and there is only one other re-review by @bnb to come in. I wanted to make a start on the CI/CD document. The feedback is we need real examples and so I have been working, as a part of the expressJS triage team, to learn how to carry out full CI/CD on the GitHub actions platform. I have been working in an [integration test repo](https://github.com/ghinks/express-integration-store) so that we have some hard examples of not just regular unit test and lint operations but we have npm and docker image publication then integration tests using those images.

**Comment by lholmquist** [comment]
should the deprecation guidelines also be part of the promotion list?

**Comment by thescientist13** [comment]
@lholmquist that 
Oh yes, good call.  I suppose an issue should be made for that one as well... so done and added!  ( #431)

**Comment by jonchurch** [comment]
I'd love to see our best practices be living documents. I think it's a good idea to promote most of these and just keep updating them as necessary, to lower the inertia around publishing only when they're "done".
